spring.application.name=archive-ledger

####################################################
# Server
####################################################

server.port=8081

####################################################
# Database
####################################################

spring.datasource.url=jdbc:mysql://localhost:3306/archive_ledger?useSSL=false&serverTimezone=Asia/Tehran&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

####################################################
# JPA
####################################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

####################################################
# Jackson
####################################################

spring.jackson.serialization.indent-output=true


##################################################
# Report Engine
##################################################

report.output.path=src/main/resources/static/report/datas
#report.output.path=target/classes/static/report/datas
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

##################################################
# prefix  suffix
##################################################
#spring.mvc.view.prefix=
#spring.mvc.view.suffix=
#spring.web.resources.static-locations=